In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

2026-02-28 15:22:21.372159: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-28 15:22:21.428747: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-28 15:22:21.429625: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-28 15:22:22.128453: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

### **Carga y limpieza de datos:**

Dentro del conjunto de datos seleccionado, las variables *transaction_id* y *user_id* se consideran irrelevantes para el entrenamiento del modelo. En el caso de transaction_id, su inclusión podría inducir overfitting, ya que se trata de un identificador único sin valor predictivo real. Por su parte, user_id requeriría un volumen significativamente mayor de información histórica para modelar patrones de reincidencia de manera confiable, por lo que también se excluye del análisis.

Las variables *(transaction_amount, account_age_days, transaction_hour, previous_failed_attempts, avg_transaction_amount, ip_risk_score, login_attempts_last_24h)* corresponden a datos numéricos continuos o discretos, los cuales son directamente utilizables y evaluables por la red neuronal tras un proceso adecuado de normalización o estandarización.

En contraste, las variables *(transaction_type, payment_mode, device_type, device_location)* son de tipo categórico (string). Para poder incorporarlas al modelo, se transforman mediante un mapeo numérico apropiado, permitiendo su procesamiento dentro de la arquitectura neuronal.

La variable *is_international* es de naturaleza binaria y puede ser utilizada directamente como característica de entrada, ya que representa información relevante en formato compatible con el modelo.

En consecuencia, todas las variables mencionadas constituyen los features del modelo. La variable objetivo se encuentra en la última columna bajo el nombre *fraud_label*, la cual representa una salida binaria que indica si la transacción corresponde o no a un caso de fraude.

In [2]:
df=pd.read_csv('Datasets/Digital_Payment_Fraud_Detection_Dataset.csv')
#cols_str= [transaction_type, payment_mode, device_type, device_location]
#print(df.dtypes)
df=df.drop(columns=['transaction_id', 'user_id'])

for i in df.columns:
    if df[i].dtype== object:
        unicos=df[i].unique()
        mapeo={}
        c=0
        for j in unicos:
            mapeo[j]=c
            c+=1
        #print(i, df[i].dtype, mapeo)
        df[f'{i}_cat']=df[i].replace(mapeo)
        df=df.drop(columns=i)

df.head(2)

,transaction_amount,account_age_days,transaction_hour,previous_failed_attempts,avg_transaction_amount,is_international,ip_risk_score,login_attempts_last_24h,fraud_label,transaction_type_cat,payment_mode_cat,device_type_cat,device_location_cat
0,18758.28,895,14,1,25535.84,0,0.718,4,0,0,0,0,0
1,47538.18,918,21,0,3955.85,0,0.525,9,0,1,1,1,0

### **Datos de ensayo y verificación**

In [3]:
rand_sel=np.random.rand(len(df))*7
rand_sel=rand_sel.astype(int)
df['random']=rand_sel
df_princ=df[df['random']<4].copy().drop(columns='random')
df_1=df[df['random']==4].copy().drop(columns='random')
df_2=df[df['random']==5].copy().drop(columns='random')
df_3=df[df['random']==6].copy().drop(columns='random')

In [4]:
print(  len(df_princ[df_princ['fraud_label']==1]),
        len(df_princ[df_princ['fraud_label']==0]), '\n',
        len(df_1[df_1['fraud_label']==1]), 
        len(df_1[df_1['fraud_label']==0]), '\n',
        len(df_2[df_2['fraud_label']==1]), 
        len(df_2[df_2['fraud_label']==0]), '\n',
        len(df_3[df_3['fraud_label']==1]),
        len(df_3[df_3['fraud_label']==0]))

290 3972
 59 1039
 74 1004
 66 996

### **Definición del modelo:**

Se procede a definir el modelo, con los datos categorizados y la unica salida binaria

In [5]:
x=[]
for i in df_princ.columns:
    if i!= 'fraud_label':
        x.append(df_princ[i])

X=np.column_stack(x)
tamaño= len(x)

In [44]:
entrada = tf.keras.layers.Dense(units=tamaño, input_shape=[tamaño])
c1 = tf.keras.layers.Dense(units=tamaño)
c2 = tf.keras.layers.Dense(units=tamaño)
c3 = tf.keras.layers.Dense(units=tamaño)
salida = tf.keras.layers.Dense(units=1)
red = tf.keras.Sequential([entrada, c1, c2, c3, salida])
red.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

In [ ]:
historial = red.fit(X, df_princ['fraud_label'], epochs=10000, verbose=False)

In [37]:
fila=25
cols_ver=['transaction_amount', 'account_age_days', 'transaction_hour', 'previous_failed_attempts', 'avg_transaction_amount', 'is_international', 'ip_risk_score', 'login_attempts_last_24h', 'transaction_type_cat', 'payment_mode_cat','device_type_cat','device_location_cat']
k=df_1[cols_ver].iloc[[fila]].values

k2=df_1[['fraud_label']].iloc[fila].values
print(k,'\n'*2, k2)
red.predict(k)

[[3.049774e+04 1.811000e+03 1.100000e+01 3.000000e+00 4.199500e+02
  0.000000e+00 3.330000e-01 9.000000e+00 0.000000e+00 1.000000e+00
  0.000000e+00 0.000000e+00]]

 [1]
1/1 [==============================] - 0s 14ms/step

array([[0.17880355]], dtype=float32)

In [43]:

def clasificar_dataframe(df, modelo, columnas):
    X = df[columnas].values
    preds = modelo.predict(X)
    df['clasificacion'] = preds#(preds > 0.5).astype(int)
    return df

df_1= clasificar_dataframe(df_1, red, cols_ver)

df_1[df_1['clasificacion']<-0.5].reset_index().head(50)

35/35 [==============================] - 0s 706us/step

,index,transaction_amount,account_age_days,transaction_hour,previous_failed_attempts,avg_transaction_amount,is_international,ip_risk_score,login_attempts_last_24h,fraud_label,transaction_type_cat,payment_mode_cat,device_type_cat,device_location_cat,clasificacion
0,56,4470.20,313,5,3,29963.03,0,0.937,9,0,1,2,1,2,-0.643615
1,119,26990.14,1992,15,4,28030.84,0,0.300,9,0,1,3,1,0,-0.505986
2,185,33016.20,1044,5,3,29438.33,0,0.984,1,0,0,3,1,2,-0.541695
3,188,26506.05,1989,20,3,29320.95,0,0.826,7,0,2,0,0,4,-0.539786
4,255,27862.22,922,0,2,29744.29,0,0.854,3,1,1,1,1,2,-0.565128
5,291,1915.54,1489,6,2,26902.69,0,0.211,6,0,2,0,0,2,-0.553849
6,332,768.95,1648,23,1,25641.68,0,0.295,6,0,1,0,1,1,-0.523427
7,339,4936.82,467,3,2,27168.06,0,0.157,3,0,0,3,1,2,-0.570630
8,345,30811.71,241,14,3,29279.81,0,0.980,9,0,2,0,1,2,-0.559455
9,434,4251.13,151,13,3,24239.34,0,0.400,8,0,1,2,2,3,-0.507241
10,511,20941.24,1931,21,3,27696.50,0,0.733,9,0,0,3,2,0,-0.514816
11,545,17940.23,847,16,0,26978.64,0,0.996,7,0,0,0,2,0,-0.524951
12,603,4480.69,957,23,2,29611.01,0,0.274,5,0,1,1,0,4,-0.624080
13,762,12462.03,1990,9,2,26943.95,0,0.769,5,0,0,3,1,0,-0.516976
14,776,11501.11,1448,1,3,27268.19,0,0.133,8,0,1,1,1,4,-0.537928
15,819,16793.10,567,6,2,29699.74,0,0.164,9,0,1,2,0,3,-0.599819
16,835,20975.33,1733,6,3,28672.24,0,0.143,3,0,1,0,0,4,-0.542547
17,994,18080.65,376,9,0,27591.24,0,0.495,1,0,2,1,2,4,-0.548971
18,1216,4164.93,734,23,3,25689.63,1,0.060,8,1,1,3,2,3,-0.534934
19,1241,38841.01,925,13,4,29274.62,0,0.068,8,0,2,1,1,4,-0.525691
20,1494,30192.26,308,5,3,29469.78,0,0.776,7,0,2,1,0,0,-0.563896
21,1530,15599.82,484,22,3,29093.15,0,0.753,2,0,2,1,2,2,-0.591293
22,1577,32116.48,419,23,3,28625.40,0,0.422,5,0,1,2,0,0,-0.536644
23,1648,39112.30,1620,17,0,29011.42,0,0.869,4,0,1,1,2,4,-0.505134
24,1650,1856.21,862,4,2,29783.77,0,0.578,8,0,1,0,1,1,-0.636002
25,1656,27712.42,410,11,4,28374.69,0,0.443,1,0,0,2,1,4,-0.542055
26,1675,15268.72,1636,10,4,28208.42,0,0.870,8,0,2,0,2,2,-0.548430
27,1714,2955.28,1179,10,3,28203.73,1,0.062,3,0,2,0,1,4,-0.591758
28,1800,47827.24,23,16,1,29993.93,0,0.675,5,0,2,2,2,1,-0.535973
29,1870,40898.38,1489,6,3,29914.21,0,0.056,9,0,1,1,2,4,-0.524815
30,2057,20617.69,995,6,4,28141.61,0,0.172,9,0,2,3,1,2,-0.543984
31,2068,8277.08,1756,12,1,26110.91,0,0.598,5,0,2,2,2,0,-0.512672
32,2105,15872.25,1816,15,0,29979.00,0,0.697,5,0,0,3,2,0,-0.585895
33,2110,7078.54,1341,7,3,25542.51,0,0.190,4,0,1,3,1,1,-0.509304
34,2126,31751.83,611,18,3,28503.28,0,0.116,4,0,0,1,0,2,-0.530839
35,2222,4871.90,726,22,3,27850.39,0,0.380,5,0,2,0,1,0,-0.584435
36,2290,30558.46,335,4,1,28458.36,0,0.292,8,0,0,2,2,0,-0.536878
37,2318,21120.32,1315,1,2,28086.42,0,0.632,1,0,1,3,2,0,-0.534884
38,2322,30414.87,1437,15,4,29936.57,0,0.183,8,0,0,3,2,2,-0.554064
39,2406,18261.46,1469,15,3,29024.98,0,0.538,4,0,0,0,0,4,-0.563357
40,2441,27108.16,913,20,1,28955.59,0,0.229,3,0,0,3,2,1,-0.548414
41,2642,39102.10,198,9,1,29844.65,0,0.532,5,0,0,1,2,3,-0.551474
42,2668,36942.94,319,8,2,28439.18,0,0.037,9,0,0,0,0,3,-0.520289
43,2772,40357.93,439,22,1,29941.65,0,0.105,3,0,2,0,1,0,-0.547227
44,2931,33067.66,460,23,3,29723.55,0,0.832,2,0,0,3,1,3,-0.560297
45,3054,32854.97,380,1,3,27674.87,0,0.843,7,0,0,2,0,4,-0.510784
46,3174,3571.07,902,10,2,26196.05,0,0.473,1,0,2,2,2,2,-0.543397
47,3393,16298.27,520,3,0,26363.81,0,0.750,2,1,1,1,2,0,-0.520026
48,3410,20589.02,981,5,0,29002.88,0,0.022,1,0,1,0,2,0,-0.565338
49,3413,18053.32,823,14,4,27286.92,0,0.232,5,0,1,1,2,4,-0.533666